repos:
      - repo: https://github.com/psf/black
        rev: stable
        hooks:
          - id: black
      -   repo: https://github.com/pre-commit/pre-commit-hooks
          rev: v2.0.0
          hooks:
          - id: trailing-whitespace
          - id: check-case-conflict
          - id: check-docstring-first
          - id: check-yaml
          - id: debug-statements
          - id: end-of-file-fixer
          - id: requirements-txt-fixer
          - id: detect-private-key
          - id: double-quote-string-fixer
          - id: flake8
